#!/usr/bin/env python3
"""
Generate test data for benchmark_sources/generic_cpp/programs/erosion_redmin.

Grayscale erosion (uint8, 1 channel) with a flat, centred k x k structuring element, as in
OpenCV cv::erode with a rectangular kernel and the default border (outside pixels never win).
The reference is computed with SciPy, scipy.ndimage.grey_erosion(mode='constant', cval=255),
and cross-checked against a plain-Python minimum over the clipped window.

  sweep A: 32x32 image, k in {3, 5, 7, 9, 15}
  sweep B: k = 3, image 16x16, 64x64 and a non-square 24x40

Needs numpy + scipy, so run it on the host (not in the container).
Deterministic: fixed seed, so re-running reproduces identical files.

Usage: python3 scripts/gen_erosion.py
"""
import csv
from pathlib import Path

import numpy as np
import scipy
from scipy import ndimage

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "benchmark_sources" / "generic_cpp" / "programs" / "erosion_redmin" / "test_data"

SEED = 20261007
CASES = [("A", 32, 32, k) for k in (3, 5, 7, 9, 15)] + \
        [("B", h, w, 3) for h, w in ((16, 16), (64, 64), (24, 40))]


def plain_erosion(img, k):
    h, w = img.shape
    r = k // 2
    return np.array([[img[max(0, y - r):y + r + 1, max(0, x - r):x + r + 1].min()
                      for x in range(w)] for y in range(h)], dtype=np.uint8)


def fmt(vals):
    vals = [int(v) for v in vals]
    return ",\n".join(", ".join(str(v) for v in vals[i:i + 16]) for i in range(0, len(vals), 16))


def main():
    rng = np.random.default_rng(SEED)
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("test_data_*.cpp"):
        old.unlink()

    rows = []
    for num, (exp, h, w, k) in enumerate(CASES):
        img = rng.integers(0, 256, size=(h, w), dtype=np.uint8)
        ref = ndimage.grey_erosion(img, size=(k, k), mode="constant", cval=255)
        assert np.array_equal(ref, plain_erosion(img, k))
        (OUT / f"test_data_{num}.cpp").write_text(f"""#include "test_data.hpp"
// Generated by scripts/gen_erosion.py -- do not edit.
// Test {num}: sweep {exp}, {h}x{w} image, k = {k}; reference: SciPy {scipy.__version__} ndimage.grey_erosion
const uint8_t test_input[] = {{
{fmt(img.ravel())}
}};

const uint8_t test_reference[] = {{
{fmt(ref.ravel())}
}};

const test_metadata test_meta = {{
.height = {h},
.width = {w},
.k = {k}
}};

const void * input_array[] = {{
(void*)test_input
}};

const void * reference_array[] = {{
(void*)test_reference
}};

const void * meta_array[] = {{
(void*)&test_meta
}};
""")
        rows.append([num, exp, h, w, k])

    with open(OUT / "INDEX.csv", "w", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["test", "sweep", "height", "width", "k"])
        wr.writerows(rows)
    print(f"{len(rows)} tests -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
