#!/usr/bin/env python3
"""
Generate test data for benchmark_sources/generic_cpp/programs/redminmax_micro.

Each setting (op, SEW, LMUL, vl) becomes two tests, reps 16 and 272, so that
cycles per reduction = (C(272) - C(16)) / 256 (two-point method).

  Experiment A: all 4 ops x SEW 8/16/32 x LMUL 1/2/4/8 at vl = VLMAX
  Experiment B: vredmax, LMUL 8, vl sweep per SEW (8, 16, 32)

Writes test_data/test_data_<N>.cpp (one ctest each) and test_data/INDEX.csv.
Deterministic: fixed seed, so re-running reproduces identical files.

Usage: python3 scripts/gen_redminmax_micro.py
"""
import csv
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "benchmark_sources" / "generic_cpp" / "programs" / "redminmax_micro" / "test_data"

SEED = 20261007
VLEN = 128                   # VREG_W in processor_models/vector_config.cmake
REPS = (16, 272)             # two-point method; both multiples of the x8 unroll

OPS = {"vredmax": 0, "vredmaxu": 1, "vredmin": 2, "vredminu": 3}
SEWS = (8, 16, 32)
LMULS = (1, 2, 4, 8)

VL_SWEEP = {                 # Experiment B: pairs n / n+1 straddle 32-bit chunk boundaries
    8:  (1, 2, 3, 4, 5, 8, 9, 16, 17, 32, 33, 64, 65, 127, 128),
    16: (1, 2, 3, 4, 5, 8, 9, 16, 17, 32, 33, 63, 64),
    32: (1, 2, 3, 4, 5, 8, 9, 16, 17, 31, 32),
}


def vlmax(sew, lmul):
    return VLEN * lmul // sew


def settings():
    for op in OPS:
        for sew in SEWS:
            for lmul in LMULS:
                yield "A", op, sew, lmul, vlmax(sew, lmul)
    for sew, vls in VL_SWEEP.items():
        for vl in vls:
            yield "B", "vredmax", sew, 8, vl


def make_case(rng, op, sew, lmul, vl):
    """Data (VLMAX elements), seed and reference for one setting.

    The winning element sits at a random index < vl (sometimes the last one) and is unique.
    When vl < VLMAX, an even better value is placed past vl: it must NOT win.
    The seed is strictly worse than the winner, so returning the seed fails.
    """
    signed = op in ("vredmax", "vredmin")
    is_max = op in ("vredmax", "vredmaxu")
    lo, hi = (-(1 << (sew - 1)), (1 << (sew - 1)) - 1) if signed else (0, (1 << sew) - 1)
    n = vlmax(sew, lmul)

    # Keep a margin at both ends so the winner, the past-vl trap and the seed fit strictly.
    span = hi - lo
    inner_lo, inner_hi = lo + span // 8, hi - span // 8
    data = [rng.randint(inner_lo, inner_hi) for _ in range(n)]

    win_idx = vl - 1 if rng.random() < 0.25 else rng.randrange(vl)
    if is_max:
        data[win_idx] = rng.randint(inner_hi + 1, hi - 2)
        trap = hi                                     # bigger than the winner
        seed = rng.randint(lo, inner_lo - 1)          # smaller than everything
    else:
        data[win_idx] = rng.randint(lo + 2, inner_lo - 1)
        trap = lo
        seed = rng.randint(inner_hi + 1, hi)
    if vl < n:
        data[rng.randrange(vl, n)] = trap

    window = data[:vl] + [seed]
    reference = max(window) if is_max else min(window)
    assert reference == data[win_idx] and reference != seed
    return signed, data, seed, reference


def to_i32(value, sew):
    """Value as int32 for the metadata. vmv.s.x keeps only the low SEW bits and the check
    compares only those, so only unsigned 32-bit values above INT32_MAX need converting."""
    if sew == 32 and value >= 1 << 31:
        value -= 1 << 32
    return value


def c_int(value):
    # INT32_MIN cannot be written as a plain negative literal
    return "(-2147483647 - 1)" if value == -(1 << 31) else str(value)


def write_cpp(path, num, exp, op, sew, lmul, vl, reps, signed, data, seed, reference):
    ctype = f"{'' if signed else 'u'}int{sew}_t"
    body = ",\n".join(", ".join(str(v) for v in data[i:i + 16]) for i in range(0, len(data), 16))
    path.write_text(f"""#include "test_data.hpp"
// Generated by scripts/gen_redminmax_micro.py -- do not edit.
// Test {num}: experiment {exp}, {op}.vs SEW {sew} LMUL {lmul} vl {vl} reps {reps}
alignas(4) const {ctype} test_data[] = {{
{body}
}};

const test_metadata test_meta = {{
.op = {OPS[op]},
.sew = {sew},
.lmul = {lmul},
.vl = {vl},
.reps = {reps},
.seed = {c_int(to_i32(seed, sew))},
.reference = {c_int(to_i32(reference, sew))}
}};

const void * data_array[] = {{
(void*)test_data
}};

const void * meta_array[] = {{
(void*)&test_meta
}};
""")


def main():
    rng = random.Random(SEED)
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("test_data_*.cpp"):
        old.unlink()

    rows = []
    num = 0
    for setting, (exp, op, sew, lmul, vl) in enumerate(settings()):
        signed, data, seed, reference = make_case(rng, op, sew, lmul, vl)
        for reps in REPS:
            write_cpp(OUT / f"test_data_{num}.cpp", num, exp, op, sew, lmul, vl, reps,
                      signed, data, seed, reference)
            rows.append([num, setting, exp, op, sew, lmul, vl, reps])
            num += 1

    with open(OUT / "INDEX.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["test", "setting", "experiment", "op", "sew", "lmul", "vl", "reps"])
        w.writerows(rows)
    print(f"{num} tests ({num // 2} settings) -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
