#!/usr/bin/env python3
"""
Generate the max pooling shape sweep for maxpool_muriscv and maxpool_redmax (shared test_data/).

Fixed: one 16x16 int8 image (NHWC), batch 1, stride = window, no padding, no clamping.
Varied: channels C x square window k. k = 16 is global pooling (one output pixel).
The reference is computed here (max over each window), so no TFLite is needed.

Files are numbered from 100 so they never collide with the imported CMSIS-NN sets (0-7).
Deterministic: fixed seed, so re-running reproduces identical files.

Usage: python3 scripts/gen_maxpool_sweep.py
"""
import csv
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "benchmark_sources" / "generic_cpp" / "programs" / "maxpool_muriscv" / "test_data"

SEED = 20261007
FIRST = 100
H = W = 16
CHANNELS = (1, 2, 4, 8, 16, 32, 64)
WINDOWS = (2, 3, 4, 8, 16)


def fmt(vals):
    return ",\n".join(", ".join(str(v) for v in vals[i:i + 16]) for i in range(0, len(vals), 16))


def maxpool(inp, c, k):
    oh, ow = H // k, W // k
    out = []
    for oy in range(oh):
        for ox in range(ow):
            for ch in range(c):
                out.append(max(inp[((oy * k + y) * W + ox * k + x) * c + ch]
                               for y in range(k) for x in range(k)))
    return oh, ow, out


def main():
    rng = random.Random(SEED)
    for old in OUT.glob("test_data_*.cpp"):
        if int(old.stem.split("_")[-1]) >= FIRST:
            old.unlink()

    rows = []
    num = FIRST
    for c in CHANNELS:
        for k in WINDOWS:
            inp = [rng.randint(-128, 127) for _ in range(H * W * c)]
            oh, ow, ref = maxpool(inp, c, k)
            meta = dict(batch=1, in_h=H, in_w=W, channels=c, filter_h=k, filter_w=k,
                        stride_h=k, stride_w=k, pad_h=0, pad_w=0, out_h=oh, out_w=ow,
                        act_min=-128, act_max=127)
            (OUT / f"test_data_{num}.cpp").write_text(f"""#include "test_data.hpp"
// Generated by scripts/gen_maxpool_sweep.py -- do not edit.
// Shape sweep: {H}x{W} image, C = {c}, window {k}x{k}, stride {k}, no padding
const int8_t test_input[] = {{
{fmt(inp)}
}};

const int8_t test_reference[] = {{
{fmt(ref)}
}};

const test_metadata test_meta = {{
""" + ",\n".join(f".{key} = {val}" for key, val in meta.items()) + """
};

const void * input_array[] = {
(void*)test_input
};

const void * reference_array[] = {
(void*)test_reference
};

const void * meta_array[] = {
(void*)&test_meta
};
""")
            rows.append([num, c, k, oh, ow])
            num += 1

    with open(OUT / "SWEEP_INDEX.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["test", "channels", "window", "out_h", "out_w"])
        w.writerows(rows)
    print(f"{num - FIRST} sweep tests ({FIRST}..{num - 1}) -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
