#!/usr/bin/env python3
"""
Convert muRISCV-NN's int8 max-pooling test data into test_data_<N>.cpp files for
benchmark_sources/generic_cpp/programs/maxpool_muriscv.

The source sets (Tests/TestData/maxpooling, maxpooling_1 .. maxpooling_7) come from CMSIS-NN
and were generated with TensorFlow Lite; each holds the layer parameters (config_data.h),
the input tensor and TFLite's expected output.

Usage: python3 scripts/import_muriscv_maxpool.py <path to muriscv-nn checkout>
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "benchmark_sources" / "generic_cpp" / "programs" / "maxpool_muriscv" / "test_data"
SETS = ["maxpooling"] + [f"maxpooling_{i}" for i in range(1, 8)]   # test N = set N

FIELDS = [  # test_metadata field, config_data.h suffix
    ("batch", "BATCH_SIZE"), ("in_h", "INPUT_H"), ("in_w", "INPUT_W"), ("channels", "INPUT_C"),
    ("filter_h", "FILTER_H"), ("filter_w", "FILTER_W"), ("stride_h", "STRIDE_H"), ("stride_w", "STRIDE_W"),
    ("pad_h", "PADDING_H"), ("pad_w", "PADDING_W"), ("out_h", "OUTPUT_H"), ("out_w", "OUTPUT_W"),
    ("act_min", "ACTIVATION_MIN"), ("act_max", "ACTIVATION_MAX"),
]


def read_array(path):
    body = re.search(r"\{(.*)\}", path.read_text(), re.S).group(1)
    return [int(v) for v in body.replace("\n", " ").split(",") if v.strip()]


def main():
    src = Path(sys.argv[1])
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=src,
                            capture_output=True, text=True).stdout.strip() or "unknown"
    OUT.mkdir(parents=True, exist_ok=True)
    for num, name in enumerate(SETS):
        d = src / "Tests" / "TestData" / name
        prefix = name.upper() + "_"
        cfg = dict(re.findall(rf"#define {prefix}(\w+) (\S+)", (d / "config_data.h").read_text()))
        meta = {field: int(cfg[key]) for field, key in FIELDS}
        inp, ref = read_array(d / "input_tensor.h"), read_array(d / "output.h")
        assert len(inp) == meta["batch"] * meta["in_h"] * meta["in_w"] * meta["channels"]
        assert len(ref) == meta["batch"] * meta["out_h"] * meta["out_w"] * meta["channels"]
        fmt = lambda vals: ",\n".join(", ".join(str(v) for v in vals[i:i + 16]) for i in range(0, len(vals), 16))
        (OUT / f"test_data_{num}.cpp").write_text(f"""#include "test_data.hpp"
// Generated by scripts/import_muriscv_maxpool.py -- do not edit.
// Source: muRISCV-NN {commit}, Tests/TestData/{name} (CMSIS-NN test data, reference from TensorFlow Lite)
const int8_t test_input[] = {{
{fmt(inp)}
}};

const int8_t test_reference[] = {{
{fmt(ref)}
}};

const test_metadata test_meta = {{
""" + ",\n".join(f".{k} = {v}" for k, v in meta.items()) + """
};

const void * input_array[] = {
(void*)test_input
};

const void * reference_array[] = {
(void*)test_reference
};

const void * meta_array[] = {
(void*)&test_meta
};
""")
        print(f"test_data_{num}.cpp <- {name}: C={meta['channels']} {meta['in_h']}x{meta['in_w']} "
              f"filter {meta['filter_h']}x{meta['filter_w']} -> {meta['out_h']}x{meta['out_w']}")


if __name__ == "__main__":
    main()
